name: hmac_drgb
description: dart implementation of [HMAC DRBG]. dart implementation of [HMAC DRBG].
version: 1.0.0
homepage: https://github.com/litaoh/hmac_drgb

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  hash: ^1.0.0

dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.6.0
